#!/usr/bin/env python3

import os
import sys

def usage():
    print(f"usage: {sys.argv[0]} [port]")
    sys.exit()

if (len(sys.argv) < 2 or len(sys.argv) > 3):
    usage()

port = int(sys.argv[1]) + 1
cmd = "./gradlew cli --console=plain -q --no-daemon "
if len(sys.argv) == 3 and sys.argv[2] == '-f':
    cmd += f' --args="-p {port} -f"'
else:
    cmd += f' --args="-p {port}"'
print(cmd)
os.system(cmd)
